version: '3'
services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  frontend-pi:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports: 
      - '8080:80'
  backend-pi:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    env_file:
      - ./api/.env
    ports: 
      - '3001:3001'
